# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Zipei Geng
title: Master's Student
email: zigeng@student.ethz.ch
website: zpgeng.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: ZipeiGeng
github_username:  zpgeng
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: zipeigeng
# flickr_username: jekyll
instagram_username: gengzipei
linkedin_username: zipei-fred-geng-182271102
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am **Zipei (Fred) Geng**, a student at ETH Zürich major in **Statistics & Data Science**. 
  
  My main focused areas are computational statistics, statistical machine learning (e.g. Lasso & NLP), and optimization algorithms in data science.

  I am most skilled in: <mark>Python / R</mark> and <mark>Watching / Commentating Football Matches</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Eye Gaze Estimation Using Electroencephalography Signals
        # link: 
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Making eye gaze position prediction using EEG data synthesized from human brain.
        description: | # this will include new lines to allow paragraphs
          - At present, the overarching goal is to provide a state-of-the-art EEG based eye tracking approach that makes use of neural networks to classify the direction of gaze (left or right) on the computer screen. This in turn could accelerate scientific discovery on perceptual, attentional, cognitive processes particularly during free viewing of complex stimuli (i.e. naturalistic paradigms) and in clinical settings, in which the installation of an eye-tracker is impractical (e.g. hospital bed).
  - title: 
    layout: list
    content:
      - layout: top-middle    
        title: Human Gesture Recognition
        quote: >
          ETH Zürich Computational Intelligence Lab Course Project
        description: |
          - Proposed a novel pipeline including data preprocessing and data augmentation following by 2D convolutions and bidirectional LSTMs to classify human gestures in video format, which ranked the 1st out of 12 groups.
  
  - title:
    layout: list
    content:
      - layout: top-middle
        title: Weight Estimation Using Wheel Load Checkpoint
        quote: >
          SBB CFF FFS Research Project
        description: |
          - Dug thoroughly into the wheel load check-points system and data processing language R.
          
          - Collaboratively estimated the actual weight of the train using non-parametric and parametric denoising method. 
          
          - Independently designed novel data tailoring functions and algorithms.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PricewaterhouseCoopers
        link: https://www.pwccn.com/zh.html
        # link_text: boringcompany.com
        sub_title: Associate Intern
        caption: July 2018 - September 2018
        #quote: >
        description: | # this will include new lines to allow paragraphs
            - Facilitated the project group on testing the administration , research and development expense as well as checking the fixed assets of a start-up pharmaceutical company.
            
            - Verified the information for disclosure of employee benefits expenses by sending confirmations to related parties including banks and directors using Excel.
            
            - Effectively searched and integrated the information from the prospectus of related pharmaceutical companies which are listed in HKEX.
            
            - Proofread the 630 accountant report by locating the specific errors and adjusted the wording and format of some key parts in the report.
  
  - title:  
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Stifel GMP Securities
        link: https://www.stifel.com/institutional/StifelCanada
        # link_text: boringcompany.com
        sub_title: Associate Intern
        caption: June 2018 - Jule 2018
        #quote: >
        description: | # this will include new lines to allow paragraphs
          - Promptly performed a summary of key economic indicators of Kazakhstan in five years with high quality tables and charts highlighting historical trends by collecting and analysing raw data.
          
          - Prepared an overview presentation of a large Chinese conglomerate which is seeking potential debt financing overseas by researching company related information, performing financial analysis including capitalisation table, share price performance and EBITDA of last five years on three business entities.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ETH Zürich
        caption: 2019 - 2022
        sub_title: MSc Statistics
        quote: >
          ETH Zürich is a public research university in the city of Zürich, Switzerland. Founded by the Swiss Federal Government in 1854 with the stated mission to educate engineers and scientists, the school focuses exclusively on science, technology, engineering and mathematics.
        description: | # this will include new lines to allow paragraphs
          - GPA: 5.5/6.0

          - Relevant Coursework:
            1. Stats/Math-related: High-dimensional Statistics, Mathematical Optimization, Neural Network Theory, Time Series Analysis, Computational Statistics, Smoothing and Nonparametric Regression
          
            2. Machine Learning-related: Natural Language Processing, Intrduction to Machine Learning, Probabilistic Artificial Intelligence, Mathematical Tools in Machine Learning, Machine Perception
          
            3. Data Management & Analysis: ANOVA, Big Data for Engineers, Data Mining
    
  - title:
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The University of Manchester
        caption: 2017 - 2019
        sub_title: BSc with Honours Mathematics and Statistics
        quote: >
          The University of Manchester is a public research university in Manchester, England. It has great and immediate impact within the research community. The QS World University Rankings 2020–21 placed Manchester 29th in the world. The Academic Ranking of World Universities 2020 ranked Manchester 5th in the UK and 36th in the world.
        description: |
          - GPA: 84/100
          
          - *Be honored with 2018 School International Excellence Scholarships*
          
          - Relevant Coursework: Introduction to Financial Mathematics, Time Series Analysis, Multivariate Stat. and Machine Learning, Martingales with Applications

  - title:
    layout: list # Type of content section (list/text)
    content:
      - layout: left  
        title: Shandong University
        caption: 2015 - 2019
        sub_title: BSc Statistics
        quote: >
          Shandong University is a public research comprehensive university in Jinan, Shandong, China. It is one of the largest universities in China by student population and is supported directly by the national government. It is famous for its mathematics and natural sciences. In 2020, the Ministry of Education of P.R.C. ranked School of Mathematics of Shandong University the 3rd among all Chiniese universities.
        description: |
          - GPA: 4.52/5.0
          
          - *Be honored with Shandong University Second Prize Scholarship (2015 - 2016, 2016 - 2017)*
          
          - Relevant Coursework: PDE, ODE, Measure Theory, Mathematical Modelling, Mathematical Experiments (MATLAB)


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in machine learning and applied mathematics, some of my other interests and hobbies are:
      - Table Tennis
      - [Go (Wei Qi)](https://www.britgo.org/clubs/manchester)
        - My favourite Go player: [Masaki Takemiya (武宫正树)](https://en.wikipedia.org/wiki/Masaki_Takemiya)
      - Football
        - Favourite Club(s): [Inter Milan](https://www.inter.it/en), [Man United](https://www.manutd.com/)

      1. The noted landscape "The Forbbiden City"  from my hometown, **Beijing**  
      ![The Forbbiden City](images/gugong.jpg)

      2. My favourite Peking cuisine(s):
        - Peking Roast Duck
          ![Peking Roast Duck](images/roastduck.jpg)
        - Boiled Pork Offal with Cake Bits (卤煮火烧)
          ![Boiled Pork Offal with Cake Bits (卤煮火烧)](images/luzhu.jpg)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
