title: Zipei's Blog
description: Thoughts of learning data science and machine learning.
show_downloads: true

baseurl:  # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://zpgeng.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: 

# social
author: Zipei Geng
image:
twitter:
  username: ZipeiGeng
  
comment:
  gitment:
    enable: true
    owner: 'zpgeng' # 必填项, 你的GitHub ID
    repo: 'zpgeng.github.io' # 必填项  你的存储评论的repo
    oauth:
      client_id: '406124fff27c65dea2f8' # 必填项
      client_secret: '12d59d3a9d5fd026f5032cc5606e3efb4c41eb79' # 必填项
      redirect_uri: https://zpgeng.github.io